services:

  data-service:
    image: quangnam130520/data-service:latest
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - data-service-network


  redis:
    image: redis:7.4.0
    restart: always
    #    expose:
    #      - 6379:6379
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis/data
    networks:
      - data-service-network


volumes:
  #  db-data:
  redis-data:

networks:
  data-service-network:
    driver: bridge

#secrets.yml:
#    db-password:
#      file: db/password.txt

