server:
  port: 8080

spring:
  application:
    name: data
  main:
    banner-mode: console # Disable the Spring logo
    #        web-application-type: none
#    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://localhost:3306/data?allowpublickeyretrieval=true&usessl=false
    username: root
    password: A%9jr>NK
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true