server:
  port: 8080

spring:
  application:
    name: data
  main:
    banner-mode: console # Disable the Spring logo
    #        web-application-type: none
  #    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://localhost:3306/data?allowpublickeyretrieval=true&usessl=false
    username: root
    password: A%9jr>NK
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: football
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: true

connection:
  eightxbet:
    url: https://001xm4z27x2jy1u-api.pj51m7rx.com
    headers:
      user-Agent: Mozilla/5.0
      referer: https://8xbet00.cc/
      x-checksum: 13d730b032dda17d6a440904f27560d7df77cd0b20e56a78153be8ade717e129

  sofasocre:
    url: https://www.sofascore.com/api/v1
  local:
    url: http://localhost:8080/