server:
  port: 3002

spring:
  application:
    name: data-service
  main:
    banner-mode: console # Disable the Spring logo
    #        web-application-type: none
  #    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  #  datasource:

  #    url: jdbc:mysql://localhost:3306/data?allowpublickeyretrieval=true&usessl=false
  #    username: root
  #    password: A%9jr>NK
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    hikari:
  #      connection-timeout: 60000
  #      maximum-pool-size: 5
  cache:
    type: redis

  data:
    mongodb:
      database: ${MONGODB_DB:football}
      uri: mongodb+srv://${MONGODB_USERNAME:quangnam130520}:${MONGODB_PW:pij2bY1U5DHXOnb8}@${MONGODB_HOST:cluster0.fwoaemp.mongodb.net}/
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      client-type: lettuce
  #uri: mongodb+srv://quangnam130520:NLiXVlvZc7Xk6Z4S@cluster0.fwoaemp.mongodb.net/
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: true

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    leaseRenewalIntervalInSeconds: 10

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: info



connection:
  eightxbet:
    url: https://001xm4z27x2jy1u-api.pj51m7rx.com
    headers:
      user-Agent: Mozilla/5.0
      referer: https://8xbet00.cc/
      x-checksum: 13d730b032dda17d6a440904f27560d7df77cd0b20e56a78153be8ade717e129

  sofasocre:
    url: https://www.sofascore.com/api/v1
  local:
    url: http://localhost:8080/