apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service-master
  namespace: default
  labels:
    app: data-service-master
    environment: production

spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-service-master
  template:
    metadata:
      labels:
        app: data-service-master
    spec:
      containers:
        - name: data-service
          image: asia-east2-docker.pkg.dev/santos-435406/santos-repo/data-service-master:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: data-service-configmap
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: data-service-configmap
                  key: redis-port

---

apiVersion: v1
kind: Service
metadata:
  name: data-service-master
  labels:
    app: data-service-master

spec:
  selector:
    app: data-service-master
  ports:
    - protocol: TCP
      name: app
      port: 8080
      targetPort: 8080
  type: LoadBalancer