apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service-master # data-service
  namespace: default # testing, development, staging, production
  labels:
    app: data-service # data-service
    environment: production


spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-service # data-service
  template:
    metadata:
      labels:
        app: data-service # data-service
    spec:
      containers:
        - name: data-service
          # DATA_SERVICE_REGISTRY_PATH: asia-south1-docker.pkg.dev
          # PROJECT_ID: data-service-320209
          # REPOSITORY: jenkins
          image: asia-east2-docker.pkg.dev/santossv/santos/data-service-master:latest
          ports:
            - containerPort: 8080 # 8080
          #          restartPolicy: Always
          imagePullPolicy: IfNotPresent

          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: data-service-configmap
                  key: redis-host

            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: data-service-configmap
                  key: redis-port

            #resources:
            #requests:
            #memory: "64Mi"
            #cpu: "250m"
            #limits:
            #memory: "128Mi"
            #cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: data-service
  labels:
    app: data-service

spec:
  selector:
    app: data-service
  ports:
    - protocol: TCP
      name: app
      port: 8080 # service port
      targetPort: 8080 # container port
  type: LoadBalancer