apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
  namespace: default # testing, development, staging, production
  labels:
    app: data-service
    environment: production


spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
    spec:
      containers:
        - name: data-service
          image: quangnam130520/data-service:latest
          ports:
            - containerPort: 8080
          #          restartPolicy: Always
          imagePullPolicy: IfNotPresent
          #env:
            #- name: SERVER_PORT
              #value: "8080"
            #- name: SPRING_PROFILES_ACTIVE
              #value: "prod"

          #resources:
            #requests:
              #memory: "64Mi"
              #cpu: "250m"
            #limits:
              #memory: "128Mi"
              #cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: data-service
  labels:
    app: data-service

spec:
  selector:
    app: data-service
  ports:
    - protocol: TCP
      name: app
      port: 8080
      targetPort: 8080
  type: LoadBalancer
