apiVersion: v1
kind: Service
metadata:
  name: data-service
  labels:
    app: data-service

spec:
  selector:
    app: data-service
  ports:
    - protocol: TCP
      name: app
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: redis
      port: 6379
      targetPort: 6379
  type: LoadBalancer